<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test_Tuya.Application\Test_Tuya.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Presenters\" />
  </ItemGroup>

</Project>
